version: "2"

run:
  concurrency: 4
  timeout: 10m
  build-tags: [integration, helmtests]

linters:
  default: all
  disable:
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - godot
    - godox
    - gomoddirectives
    - gomodguard # Replaced by gomodguard_v2, enabled with default: all
    - gosec
    - ireturn
    - lll
    - mnd
    - musttag
    - nestif
    - nilerr
    - nlreturn
    - prealloc
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    paralleltest:
      ignore-missing: true
      ignore-missing-subtests: true
    tagliatelle:
      case:
        rules:
          json: camel
        use-field-name: true
    testifylint:
      disable:
        - require-error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "SA1019:"
        paths:
          - internal/session/manager.go
          - internal/session/manager_test.go
      - linters:
          - dupl
          - funlen
          - maintidx
        source: ^func Test
      - linters:
          - dupl
          - funlen
          - gocognit
          - goconst
          - maintidx
        path: (.+)_test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/openkcm/gateway-extension)
        - blank
        - dot
        - alias
        - localmodule
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
