# syntax=docker/dockerfile:1

FROM golang:1.26 AS builder

WORKDIR /app

ENV GOCACHE=/root/.cache/go-build

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=bind,target=. \
    CGO_ENABLED=0 \
    go build -o /bin/extauthz ./cmd/extauthz

FROM gcr.io/distroless/static-debian12:debug AS runner

USER nonroot:nonroot

COPY --from=builder /bin/extauthz /bin/extauthz

EXPOSE 8080
EXPOSE 9092
ENTRYPOINT ["/bin/extauthz"]
