---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "extauthz.serviceAccountName" . }}-jwtprovider-clusterrole
rules:
- apiGroups: [ "{{ .Values.config.jwtk8sProvidersAPIGroup | default "gateway.extensions.envoyproxy.io" }}" ]
  resources: [ "{{ .Values.config.jwtk8sProvidersName | default "jwtproviders" }}" ]
  verbs: ["get", "list"]
