name: Helm test

on:
  push:

permissions:
  contents: read

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
      - name: Run the helm unit tests
        run: go test -v -count=1 -race -tags=helmtests ./helm-tests/unit/...
      - name: Build the Docker image
        run: docker build --no-cache -f Dockerfile.dev -t localhost/extauthz:latest .
      - name: Setup k3s
        uses: nolar/setup-k3d-k3s@62c9d1bd2bc843275c85d2e7dcd696edc1160eee # v1.1.0
        with:
          k3d-name: k3scluster
      - name: Check k3s
        run: |
          k3d --version
          while ! kubectl get serviceaccount default >/dev/null; do sleep 1; done
      - name: Import the Docker image
        run: k3d image import localhost/extauthz:latest -c k3scluster
      - name: Run the helm integration tests
        run: go test -timeout 15m -v -count=1 -race -tags=helmtests ./helm-tests/integration/...
